/**
 * Utilisateurs autorisés (connexion uniquement par nom d'utilisateur).
 * Ajoute ou modifie les utilisateurs selon tes besoins.
 */
window.USERS = {
  
  //ACCES ADMINISTRATEUR

  "tirbuce": { levels: "all"},
  "brice": {levels: "all" },
  "bbappia": { levels: "all" },
  "paterne": { levels: ["all"]},


//ACCES A1-Base Santé


//ACCES A2-Niveau moyen


//ACCES L1-Niveau Émergent

"YAPACHL18103": {levels: ["L1-Niveau Émergent"] },
"OUASALL13782": {levels: ["L1-Niveau Émergent"] },
"SEKSONL13656": {levels: ["L1-Niveau Émergent"] },
"GRASANL17380": {levels: ["L1-Niveau Émergent"] },
"ASSCLEL16884": { levels: ["L1-Niveau Émergent"] },
"KOUAKOL10467": { levels: ["L1-Niveau Émergent"] },
"GBODOML14998": { levels: ["L1-Niveau Émergent"] },
"KOFNDAL13090": { levels: ["L1-Niveau Émergent"] },
"NGASOPL19545": { levels: ["L1-Niveau Émergent"] },
"AKAANEL10933": { levels: ["L1-Niveau Émergent"] },
"GBAJOEL19775": { levels: ["L1-Niveau Émergent"] },
"KOUKOUL18722": { levels: ["L1-Niveau Émergent"] },
"NAHJUDL10903": { levels: ["L1-Niveau Émergent"] },
"BOFPAUL13489": { levels: ["L1-Niveau Émergent"] },
"TAOABIL14571": { levels: ["L1-Niveau Émergent"] },
"DAGANGL16554": { levels: ["L1-Niveau Émergent"] },
"NOUERYL13708": { levels: ["L1-Niveau Émergent"] },
"ETTDJAL11930": { levels: ["L1-Niveau Émergent"] },
"TIEKOUL17708": { levels: ["L1-Niveau Émergent"] },
"NIAFAML16842": { levels: ["L1-Niveau Émergent"] },
"COUFATL17653": { levels: ["L1-Niveau Émergent"] },
"KONCLÉL15503": { levels: ["L1-Niveau Émergent"] },
"KROTIEL17505": { levels: ["L1-Niveau Émergent"] },
"KOUTIML16862": { levels: ["L1-Niveau Émergent"] },
"KAKYANL17335": { levels: ["L1-Niveau Émergent"] },
"KOUISSL14192": { levels: ["L1-Niveau Émergent"] },
"KOFAKAL10624": { levels: ["L1-Niveau Émergent"] },
"YAPLINL18090": { levels: ["L1-Niveau Émergent"] },
"DATKOFL17445": { levels: ["L1-Niveau Émergent"] },
"SASSYLL17324": { levels: ["L1-Niveau Émergent"] },
"DIAHADL18646": { levels: ["L1-Niveau Émergent"] },
"SOUMINL19164": { levels: ["L1-Niveau Émergent"] },
"GBALOUL12588": { levels: ["L1-Niveau Émergent"] },
"KAMOIKL12113": { levels: ["L1-Niveau Émergent"] },
"AMAAKOL18139": { levels: ["L1-Niveau Émergent"] },
"ATTMARL18780": { levels: ["L1-Niveau Émergent"] },
"YAPACHL14739": { levels: ["L1-Niveau Émergent"] },
"KOUJOSL19597": { levels: ["L1-Niveau Émergent"] },
"SIAARLL19725": { levels: ["L1-Niveau Émergent"] },
"TANKOFL12518": { levels: ["L1-Niveau Émergent"] },
"ASSNOUL11313": { levels: ["L1-Niveau Émergent"] },
"TRAKADL18826": { levels: ["L1-Niveau Émergent"] },
"GUEDIAL11277": { levels: ["L1-Niveau Émergent"] },
"YAHTAML16180": { levels: ["L1-Niveau Émergent"] },
"CISHAWL19637": { levels: ["L1-Niveau Émergent"] },
"YEBJUSL17421": { levels: ["L1-Niveau Émergent"] },
"DAHERYL19644": { levels: ["L1-Niveau Émergent"] },
"KOUKOSL16718": { levels: ["L1-Niveau Émergent"] },
"YAOAYAL10916": { levels: ["L1-Niveau Émergent"] },
"YAOKOUL14147": { levels: ["L1-Niveau Émergent"] },
"NOUCHAL19351": { levels: ["L1-Niveau Émergent"] },
"KOUAMAL16048": { levels: ["L1-Niveau Émergent"] },
"KOUJUSL13137": { levels: ["L1-Niveau Émergent"] },
"KOUAMOL12344": { levels: ["L1-Niveau Émergent"] },
"DONYAHL16089": { levels: ["L1-Niveau Émergent"] },
"SAWMAHL11011": { levels: ["L1-Niveau Émergent"] },
"KADTRAL12728": { levels: ["L1-Niveau Émergent"] },
"KOUAFFL11117": { levels: ["L1-Niveau Émergent"] },
"KOUNDAL16475": { levels: ["L1-Niveau Émergent"] },
"KLAASSL19537": { levels: ["L1-Niveau Émergent"] },
"BASCLAL12458": { levels: ["L1-Niveau Émergent"] },
"TOKPAUL16002": { levels: ["L1-Niveau Émergent"] },



  //ACCES L2-Niveau Ascendant


  "DAMFANL22644": { levels: ["L2-Niveau Ascendant"] },
  "KONAMOL27378": {levels: ["L2-Niveau Ascendant"]},
  "KAMBINL20052": {levels: ["L2-Niveau Ascendant"]},
  "BONRUSL28384": {levels: ["L2-Niveau Ascendant"]},
  "KOFMARL25613": { levels: ["L2-Niveau Ascendant"]},
  "NDINADL29738": {levels: ["L2-Niveau Ascendant"] },
  "KOUYAOL27276": {levels: ["L2-Niveau Ascendant"] },
  "TOUMAKL20169": {levels: ["L2-Niveau Ascendant"] },
  "OUAADJL25621": {levels: ["L2-Niveau Ascendant"] },
  "BASLUCL20850": {levels: ["L2-Niveau Ascendant"] },
  "ANGYOUL29170": {levels: ["L2-Niveau Ascendant"] },
  "KONSACL28441": {levels: ["L2-Niveau Ascendant"] },
  "EKIRITL28681": {levels: ["L2-Niveau Ascendant"] },
  "ANGALIL27956": {levels: ["L2-Niveau Ascendant"] },
  "SERGUIL26978": {levels: ["L2-Niveau Ascendant"] },
  "MAKLOLL26421": {levels: ["L2-Niveau Ascendant"] },
  "SERANGL23587": {levels: ["L2-Niveau Ascendant"] },
  "OUADJEL27634": {levels: ["L2-Niveau Ascendant"] },
  "SORYOHL21179": {levels: ["L2-Niveau Ascendant"] },
  "KOUAKIL29836": {levels: ["L2-Niveau Ascendant"] },
  "NIATANL29711": {levels: ["L2-Niveau Ascendant"] },
  "ATSCHIL20821": {levels: ["L2-Niveau Ascendant"] },
  "KOUANGL27058": {levels: ["L2-Niveau Ascendant"] },
  "OUAMARL25853": {levels: ["L2-Niveau Ascendant"] },
  "NGUDEBL24301": {levels: ["L2-Niveau Ascendant"] },
  "KPIYOUL20707": {levels: ["L2-Niveau Ascendant"] },
  "YAPANGL21649": {levels: ["L2-Niveau Ascendant"] },
  "KONSARL25431": {levels: ["L2-Niveau Ascendant"] },
  "SONLOGL27307": {levels: ["L2-Niveau Ascendant"] },
  "TOUPENL28476": {levels: ["L2-Niveau Ascendant"] },
  "TIELOUL24531": {levels: ["L2-Niveau Ascendant"] },
  "BAKOUML22605": {levels: ["L2-Niveau Ascendant"] },
  "KOUAMAL28535": {levels: ["L2-Niveau Ascendant"] },
  "CAMSEKL24574": {levels: ["L2-Niveau Ascendant"] },
  "YAPASSL27613": {levels: ["L2-Niveau Ascendant"] },
"YAPAPOL28219": { levels: ["L2-Niveau Ascendant"] },
"ASSROLL26851": { levels: ["L2-Niveau Ascendant"] },
"FOFMAIL24281": { levels: ["L2-Niveau Ascendant"] },
"TANABEL22518": { levels: ["L2-Niveau Ascendant"] },
"DEHAUDL22115": { levels: ["L2-Niveau Ascendant"] },
"KOUKOFL22817": { levels: ["L2-Niveau Ascendant"] },
"YAPCHIL20278": { levels: ["L2-Niveau Ascendant"] },
"KOUAHOL29836": { levels: ["L2-Niveau Ascendant"] },
"NDAKOUL29932": { levels: ["L2-Niveau Ascendant"] },
"BADAFFL26705": { levels: ["L2-Niveau Ascendant"] },
"YAPSOPL25218": { levels: ["L2-Niveau Ascendant"] },
"EHOAMAL26501": { levels: ["L2-Niveau Ascendant"] },
"YAOAHOL26026": { levels: ["L2-Niveau Ascendant"] },
"BOKEULL27774": { levels: ["L2-Niveau Ascendant"] },
"AFFMYRL26553": { levels: ["L2-Niveau Ascendant"] },
"BINAKOL26305": { levels: ["L2-Niveau Ascendant"] },
"BORNAHL20384": { levels: ["L2-Niveau Ascendant"] },
"SOTCHIL28367": { levels: ["L2-Niveau Ascendant"] },
"YAPJUSL29175": { levels: ["L2-Niveau Ascendant"] },
"KINATTL20303": { levels: ["L2-Niveau Ascendant"] },
"SOUMADL25664": { levels: ["L2-Niveau Ascendant"] },
"TAIDELL20239": { levels: ["L2-Niveau Ascendant"] },
"KOUAHOL25973": { levels: ["L2-Niveau Ascendant"] },
"KOUADJL25695": { levels: ["L2-Niveau Ascendant"] },
"OUAFATL26869": { levels: ["L2-Niveau Ascendant"] },
"EVIDECL24032": { levels: ["L2-Niveau Ascendant"] },
"AGOAHOL23307": { levels: ["L2-Niveau Ascendant"] },
"ANAHENL26845": { levels: ["L2-Niveau Ascendant"] },
"KOFADJL23682": { levels: ["L2-Niveau Ascendant"] },
"BROADJL25303": { levels: ["L2-Niveau Ascendant"] },
"ATSJUNL22416": { levels: ["L2-Niveau Ascendant"] },
"YATMARL20617": { levels: ["L2-Niveau Ascendant"] },
"KOUYAHL22373": { levels: ["L2-Niveau Ascendant"] },
"SORKORL22918": { levels: ["L2-Niveau Ascendant"] },
"TRASALL24918": { levels: ["L2-Niveau Ascendant"] },
"KOUADJL25985": { levels: ["L2-Niveau Ascendant"] },
"KOUAFFL20595": { levels: ["L2-Niveau Ascendant"] },
"KPAESTL20263": { levels: ["L2-Niveau Ascendant"] },
"KOMCHAL25733": { levels: ["L2-Niveau Ascendant"] },
"AGOCELL22681": { levels: ["L2-Niveau Ascendant"] },
"OUEALIL28028": { levels: ["L2-Niveau Ascendant"] },
"BEDPAUL27506": { levels: ["L2-Niveau Ascendant"] },
"BOUAHUL24086": { levels: ["L2-Niveau Ascendant"] },
"APPYAHL22285": { levels: ["L2-Niveau Ascendant"] },
"KACAPPL26620": { levels: ["L2-Niveau Ascendant"] },
"YAOADJL28700": { levels: ["L2-Niveau Ascendant"] },
"YAOMARL26670": { levels: ["L2-Niveau Ascendant"] },
"TOUHOUL20313": { levels: ["L2-Niveau Ascendant"] },
"KOSABEL23907": { levels: ["L2-Niveau Ascendant"] },
"NIAPATL26579": { levels: ["L2-Niveau Ascendant"] },
"OUAKATL21339": { levels: ["L2-Niveau Ascendant"] },
"OUAAMIL29659": { levels: ["L2-Niveau Ascendant"] },
"KOUKOUL23402": { levels: ["L2-Niveau Ascendant"] },
"MONCHIL28775": { levels: ["L2-Niveau Ascendant"] },
"ATTAMAL22746": { levels: ["L2-Niveau Ascendant"] },
"ATSARNL27188": { levels: ["L2-Niveau Ascendant"] },
"NGUAYAL20196": { levels: ["L2-Niveau Ascendant"] },
"SEKSOPL27909": { levels: ["L2-Niveau Ascendant"] },

  //ACCES L3-Niveau Accompli SF

  "FOFMARL33911": {levels: ["L3-Niveau Accompli SF"] },
  
  //ACCES L3-Niveau Accompli IDE

  


  // Ajoute ici les nouveaux utilisateurs
};



/**
 * Informations des comptes créés localement.
 *
 * Utilisation : ajoute ici manuellement l'identifiant local, le nom, le prénom
 * et le niveau de l'utilisateur. Lorsque cet utilisateur se connecte en local,
 * son nom et son prénom s'affichent dans l'entête à la place de « Étudiant(e) ».
 *
 * Exemple à compléter :
 * window.UTILISATEURS_LOCAUX_INFOS = {
 *   "etudiant1": { nom: "KOUASSI", prenom: "Brice", niveau: "A1-Base Santé" },
 *   "etudiant2": { nom: "KOFFI", prenom: "Ange", niveau: "L2-Niveau Ascendant" }
 * };
 */
window.UTILISATEURS_LOCAUX_INFOS = window.UTILISATEURS_LOCAUX_INFOS || {
  // Ajoute ici les comptes locaux dont tu veux afficher le nom et le prénom.

   //ACCES ADMINISTRATEUR

  "tirbuce": { nom: "BEDA", prenom: "TIRBUCE PATERNE", niveau:"all"},
  "brice": {nom: "APPIA", prenom: "BRICE BEDA", niveau: "all" },
  "bbappia": { nom: "BB", prenom: "APPIA", niveau: "all" },
  "paterne": { nom: "BEDA", prenom: "TIRBUCE PATERNE", niveau:"all"},


  "YAPACHL18103": {nom: "YAPI", prenom: "ACHY", niveau:"L1-Niveau Émergent" },
  "OUASALL13782": {nom: "OUATTARA", prenom: "SALIMANTA", niveau:"L1-Niveau Émergent" },
  "SEKSONL13656": {nom: "SEKA", prenom: "SONIA CHRISTELLE", niveau: "L1-Niveau Émergent"},
  "GRASANL17380": {nom: "GRAH", prenom: "SANDRINE BOUKA TATIANA", niveau: "L1-Niveau Émergent" },
  "DAMFANL22644": { nom: "DAMBELE", prenom: "FANTA", niveau: "L2-Niveau Ascendant" },
  "KONAMOL27378": {nom: "KONAN", prenom: "AMOIN ALBERTINE", niveau: "L2-Niveau Ascendant"},
  "KAMBINL20052": {nom: "KAMAGATE", prenom: "BINTOU", niveau: "L2-Niveau Ascendant"},
  "BONRUSL28384": {nom: "BONI", prenom: "RUSTEN EVA", niveau: "L2-Niveau Ascendant"},
  "KOFMARL25613": {nom: "BINDIE", prenom: "KOFFI MARIUS", niveau: "L2-Niveau Ascendant"},
  "NDINADL29738": {nom: "N'DIORE", prenom: "NADEGE", niveau: "L2-Niveau Ascendant"},
  "KOUYAOL27276": {nom: "KOUASSI", prenom: "YAO", niveau: "L2-Niveau Ascendant"},
  "TOUMAKL20169": {nom: "TOURE", prenom: "MAKOURA", niveau: "L2-Niveau Ascendant"},
  "OUAADJL25621": {nom: "OUATTARA", prenom: "ADJARATOU", niveau: "L2-Niveau Ascendant"},
  "BASLUCL20850": {nom: "BASSOLE", prenom: "LUCIEN", niveau: "L2-Niveau Ascendant"},
  "ANGYOUL29170": {nom: "ANGOUA", prenom: "YOUHOUA", niveau: "L2-Niveau Ascendant"},
  "KONSACL28441": {nom: "KONAN", prenom: "SACOUNDE", niveau: "L2-Niveau Ascendant"},
  "EKIRITL28681": {nom: "EKISSI", prenom: "RITA", niveau: "L2-Niveau Ascendant"},
  "ANGALIL27956": {nom: "ANGOUA", prenom: "ALICE", niveau: "L2-Niveau Ascendant"},
  "SERGUIL26978": {nom: "SEREKO", prenom: "GUIHI ANNICK CAROLLE", niveau: "L2-Niveau Ascendant"},
  "MAKLOLL26421": {nom: "MAKWALA", prenom: "LOLITA AKISSI", niveau: "L2-Niveau Ascendant"},
  "SERANGL23587": {nom: "SERI", prenom: "ANGE DEBORAH", niveau: "L2-Niveau Ascendant"},
  "OUADJEL27634": {nom: "OUATTARA", prenom: "DJENEBOU ORNELLA", niveau: "L2-Niveau Ascendant"},
  "SORYOHL21179": {nom: "SORO", prenom: "YOH SARAH HYACIMINE", niveau: "L2-Niveau Ascendant"},
  "KOUAKIL29836": {nom: "KOUADIO", prenom: "AKISSI BLEDJA ZAHAI EMILIENNE", niveau: "L2-Niveau Ascendant"},
  "NIATANL29711": {nom: "NIAMIEN", prenom: "TANOA MARINA", niveau: "L2-Niveau Ascendant"},
  "ATSCHIL20821": {nom: "ATSE", prenom: "CHIBROU PULCHERIE JOSIANE", niveau: "L2-Niveau Ascendant"},
  "KOUANGL27058": {nom: "KOUAO", prenom: "ANGE BENEDICTE", niveau: "L2-Niveau Ascendant"},
  "OUAMARL25853": {nom: "OUATTARA", prenom: "MARIAM MELISSA", niveau: "L2-Niveau Ascendant"},
  "NGUDEBL24301": {nom: "N'GUETTIA", prenom: "DEBORA", niveau: "L2-Niveau Ascendant"},
  "KPIYOUL20707": {nom: "KPIN", prenom: "YOUWA ADELE", niveau: "L2-Niveau Ascendant"},
  "YAPANGL21649": {nom: "YAPO", prenom: "ANGE SEDRIQUE", niveau: "L2-Niveau Ascendant"},
  "KONSARL25431": {nom: "KONE", prenom: "SARA ELSA NOURA", niveau: "L2-Niveau Ascendant"},
  "SONLOGL27307": {nom: "SONAN", prenom: "LOGBOCHI REBECCA", niveau: "L2-Niveau Ascendant"},
  "TOUPENL28476": {nom: "TOURE", prenom: "PENANGNOUFA MADELEINE", niveau: "L2-Niveau Ascendant"},
  "TIELOUL24531": {nom: "TIE", prenom: "LOU NANYE CHRISTELLE", niveau: "L2-Niveau Ascendant"},
  "BAKOUML22605": {nom: "BAKAYOKO", prenom: "OUMAR SOUMAILA", niveau: "L2-Niveau Ascendant"},
  "KOUAMAL28535": {nom: "KOUADIO", prenom: "AMAN KRA PAULINE", niveau: "L2-Niveau Ascendant"},
  "CAMSEKL24574": {nom: "CAMARA", prenom: "SEKOU", niveau: "L2-Niveau Ascendant"},
  "YAPASSL27613": {nom: "YAPO", prenom: "ASSEMIEN FABRICE", niveau: "L2-Niveau Ascendant"},
"ASSCLEL16884": {nom: "ASSOUMOU", prenom: "CLEMENT", niveau: "L1-Niveau Émergent"},
"KOUAKOL10467": {nom: "KOUAKOU", prenom: "AKOUA FLORENCE", niveau: "L1-Niveau Émergent"},
"GBODOML14998": {nom: "GBOCHO", prenom: "DOMANH JACQUES", niveau: "L1-Niveau Émergent"},
"KOFNDAL13090": {nom: "KOFFI", prenom: "NDAH JACQUES MICHAEL", niveau: "L1-Niveau Émergent"},
"NGASOPL19545": {nom: "NGAZA", prenom: "SOPHI", niveau: "L1-Niveau Émergent"},
"AKAANEL10933": {nom: "AKA", prenom: "ANE FABRICE", niveau: "L1-Niveau Émergent"},
"GBAJOEL19775": {nom: "GBALE", prenom: "JOEL", niveau: "L1-Niveau Émergent"},
"KOUKOUL18722": {nom: "KOUADIO", prenom: "KOUAME JEAN WILLIAM", niveau: "L1-Niveau Émergent"},
"NAHJUDL10903": {nom: "NAHIN", prenom: "JUDITH ALIDA AUDREY", niveau: "L1-Niveau Émergent"},
"BOFPAUL13489": {nom: "BOFFOUO", prenom: "PAUL CONSTANT", niveau: "L1-Niveau Émergent"},
"TAOABIL14571": {nom: "TAO", prenom: "ABIBATA", niveau: "L1-Niveau Émergent"},
"DAGANGL16554": {nom: "DAGO", prenom: "ANGELE", niveau: "L1-Niveau Émergent"},
"NOUERYL13708": {nom: "NOUFE", prenom: "ERY MARIE LAURE", niveau: "L1-Niveau Émergent"},
"ETTDJAL11930": {nom: "ETTIEN", prenom: "DJAHA FLORENCE", niveau: "L1-Niveau Émergent"},
"TIEKOUL17708": {nom: "TIEMOKO", prenom: "KOUI N'DEBA ELANE", niveau: "L1-Niveau Émergent"},
"NIAFAML16842": {nom: "NIAMKE", prenom: "FAMIN ALAIN", niveau: "L1-Niveau Émergent"},
"COUFATL17653": {nom: "COULIBALY", prenom: "FATOUMATA", niveau: "L1-Niveau Émergent"},
"KONCLÉL15503": {nom: "KONE", prenom: "CLÉMENCE", niveau: "L1-Niveau Émergent"},
"KROTIEL17505": {nom: "KROU", prenom: "TIEMELET FRANCIS", niveau: "L1-Niveau Émergent"},
"KOUTIML16862": {nom: "KOUASSI", prenom: "TIMOTHE ARAVNA", niveau: "L1-Niveau Émergent"},
"KAKYANL17335": {nom: "KAKOU", prenom: "YANGA VENANCE", niveau: "L1-Niveau Émergent"},
"KOUISSL14192": {nom: "KOUASSI", prenom: "ISSA OUATTARA", niveau: "L1-Niveau Émergent"},
"KOFAKAL10624": {nom: "KOFFI", prenom: "AKABLA HORNELA", niveau: "L1-Niveau Émergent"},
"YAPLINL18090": {nom: "YAPI", prenom: "LINDA HERMINE", niveau: "L1-Niveau Émergent"},
"DATKOFL17445": {nom: "DATÉ", prenom: "KOFFI GHISLAIN", niveau: "L1-Niveau Émergent"},
"SASSYLL17324": {nom: "SASSO", prenom: "SYLVIA", niveau: "L1-Niveau Émergent"},
"DIAHADL18646": {nom: "DIABAGATE", prenom: "HADJA SETOU", niveau: "L1-Niveau Émergent"},
"SOUMINL19164": {nom: "SOULAMA", prenom: "MINATA", niveau: "L1-Niveau Émergent"},
"GBALOUL12588": {nom: "GBA", prenom: "LOU THINET NATACHA", niveau: "L1-Niveau Émergent"},
"KAMOIKL12113": {nom: "KAMELAN", prenom: "OI KAMELAN JEAN-MARCEL", niveau: "L1-Niveau Émergent"},
"AMAAKOL18139": {nom: "AMANGOA", prenom: "AKOUA", niveau: "L1-Niveau Émergent"},
"ATTMARL18780": {nom: "ATTIA", prenom: "MARIE PAULE EDWIGE", niveau: "L1-Niveau Émergent"},
"YAPACHL14739": {nom: "YAPO", prenom: "ACHIBA MARIE VICTOIRE", niveau: "L1-Niveau Émergent"},
"KOUJOSL19597": {nom: "KOUASSI", prenom: "JOSIANE ELA", niveau: "L1-Niveau Émergent"},
"SIAARLL19725": {nom: "SIA", prenom: "ARLETTE SANDRINE", niveau: "L1-Niveau Émergent"},
"TANKOFL12518": {nom: "TAN", prenom: "KOFFI CHRIST PACÔME", niveau: "L1-Niveau Émergent"},
"ASSNOUL11313": {nom: "ASSOUMOU", prenom: "NOUAMAN RODRIGUE", niveau: "L1-Niveau Émergent"},
"TRAKADL18826": {nom: "TRAORE", prenom: "KADY", niveau: "L1-Niveau Émergent"},
"GUEDIAL11277": {nom: "GUEGNI", prenom: "DIANE", niveau: "L1-Niveau Émergent"},
"YAHTAML16180": {nom: "YAH", prenom: "TAMIA ROBERTINE", niveau: "L1-Niveau Émergent"},
"CISHAWL19637": {nom: "CISSE", prenom: "HAWA", niveau: "L1-Niveau Émergent"},
"YEBJUSL17421": {nom: "YEBE", prenom: "JUSTIN", niveau: "L1-Niveau Émergent"},
"DAHERYL19644": {nom: "DAH", prenom: "ERY EMMANUELLA PELAGIE", niveau: "L1-Niveau Émergent"},
"KOUKOSL16718": {nom: "KOUASSI", prenom: "KOSSIA MARTHE", niveau: "L1-Niveau Émergent"},
"YAOAYAL10916": {nom: "YAO", prenom: "AYA NADEGE", niveau: "L1-Niveau Émergent"},
"YAOKOUL14147": {nom: "YAO", prenom: "KOUAKOU SAMUEL", niveau: "L1-Niveau Émergent"},
"NOUCHAL19351": {nom: "NOUFE", prenom: "CHARITE", niveau: "L1-Niveau Émergent"},
"KOUAMAL16048": {nom: "KOUAME", prenom: "AMA DIANE JOCELYNE", niveau: "L1-Niveau Émergent"},
"KOUJUSL13137": {nom: "KOUASSI", prenom: "JUSLIN", niveau: "L1-Niveau Émergent"},
"KOUAMOL12344": {nom: "KOUAKOU", prenom: "AMOIN ESTELLE", niveau: "L1-Niveau Émergent"},
"DONYAHL16089": {nom: "DONGO", prenom: "YAH JEANNETTE", niveau: "L1-Niveau Émergent"},
"SAWMAHL11011": {nom: "SAWADOGO", prenom: "MAHAMADOU", niveau: "L1-Niveau Émergent"},
"KADTRAL12728": {nom: "KADY", prenom: "TRAORE", niveau: "L1-Niveau Émergent"},
"KOUAFFL11117": {nom: "KOUAME", prenom: "AFFOUE CHARLOTTE", niveau: "L1-Niveau Émergent"},
"KOUNDAL16475": {nom: "KOUAME", prenom: "NDA MOREL", niveau: "L1-Niveau Émergent"},
"KLAASSL19537": {nom: "KLA", prenom: "ASSO ASTRIDE LESLIE REBECCA", niveau: "L1-Niveau Émergent"},
"YAPAPOL28219": {nom: "YAPI", prenom: "APO BEATRICE", niveau: "L2-Niveau Ascendant"},
"ASSROLL26851": {nom: "ASSANDE", prenom: "ROLANDE M'MO", niveau: "L2-Niveau Ascendant"},
"FOFMAIL24281": {nom: "FOFANA", prenom: "MAIMOUNA", niveau: "L2-Niveau Ascendant"},
"TANABEL22518": {nom: "TAN", prenom: "ABENA NADEGE", niveau: "L2-Niveau Ascendant"},
"DEHAUDL22115": {nom: "DEHI", prenom: "AUDREY", niveau: "L2-Niveau Ascendant"},
"KOUKOFL22817": {nom: "KOUAKOU", prenom: "KOFFI MARIE YABA", niveau: "L2-Niveau Ascendant"},
"YAPCHIL20278": {nom: "YAPO", prenom: "CHIA CYNTHIA", niveau: "L2-Niveau Ascendant"},
"KOUAHOL29836": {nom: "KOUASSI", prenom: "AHOU MARINA", niveau: "L2-Niveau Ascendant"},
"NDAKOUL29932": {nom: "NDA", prenom: "KOUASSI LUC", niveau: "L2-Niveau Ascendant"},
"BADAFFL26705": {nom: "BADOU", prenom: "AFFOUA RITA", niveau: "L2-Niveau Ascendant"},
"YAPSOPL25218": {nom: "YAPO", prenom: "SOPIE LEONELLE RAYMONDE", niveau: "L2-Niveau Ascendant"},
"EHOAMAL26501": {nom: "EHOUMAN", prenom: "AMA ESTELLE", niveau: "L2-Niveau Ascendant"},
"YAOAHOL26026": {nom: "YAO", prenom: "AHOU HENRIETTE", niveau: "L2-Niveau Ascendant"},
"BOKEULL27774": {nom: "BOKA", prenom: "EULOGE", niveau: "L2-Niveau Ascendant"},
"AFFMYRL26553": {nom: "AFFIDAN", prenom: "MYRIAM", niveau: "L2-Niveau Ascendant"},
"BINAKOL26305": {nom: "BINI", prenom: "AKOUA SANDRINE", niveau: "L2-Niveau Ascendant"},
"BORNAHL20384": {nom: "BORA", prenom: "NAHA", niveau: "L2-Niveau Ascendant"},
"SOTCHIL28367": {nom: "SOTAN", prenom: "CHIAKOU FRANÇOISE JOSIANE", niveau: "L2-Niveau Ascendant"},
"YAPJUSL29175": {nom: "YAPO", prenom: "JUSTIN", niveau: "L2-Niveau Ascendant"},
"KINATTL20303": {nom: "KINIMO", prenom: "ATTOUKORA SOSTHENE", niveau: "L2-Niveau Ascendant"},
"SOUMADL25664": {nom: "SOUMAHORO", prenom: "MADOUSSOU", niveau: "L2-Niveau Ascendant"},
"TAIDELL20239": {nom: "TAI", prenom: "DELPHINE", niveau: "L2-Niveau Ascendant"},
"KOUAHOL25973": {nom: "KOUAME", prenom: "AHOU MARIE CHANTAL", niveau: "L2-Niveau Ascendant"},
"KOUADJL25695": {nom: "KOUASSI", prenom: "ADJA TEHUA MARTINE", niveau: "L2-Niveau Ascendant"},
"OUAFATL26869": {nom: "OUATTARA", prenom: "FATIM AROUNA", niveau: "L2-Niveau Ascendant"},
"EVIDECL24032": {nom: "EVI", prenom: "DECHIWO MARIE GISELE", niveau: "L2-Niveau Ascendant"},
"AGOAHOL23307": {nom: "AGOH", prenom: "AHOU JULIE", niveau: "L2-Niveau Ascendant"},
"ANAHENL26845": {nom: "ANASSIN", prenom: "HENRIE-JOELLE LAETITIA", niveau: "L2-Niveau Ascendant"},
"KOFADJL23682": {nom: "KOFFI", prenom: "ADJOA BERNADETTE", niveau: "L2-Niveau Ascendant"},
"BROADJL25303": {nom: "BROU", prenom: "ADJOUA OLGA DEMIROFF", niveau: "L2-Niveau Ascendant"},
"ATSJUNL22416": {nom: "ATSE", prenom: "JUNIOR BLANCHARD", niveau: "L2-Niveau Ascendant"},
"YATMARL20617": {nom: "YATTY", prenom: "MARIE-PASCALE", niveau: "L2-Niveau Ascendant"},
"KOUYAHL22373": {nom: "KOUADIO", prenom: "YAH PRUDENCE", niveau: "L2-Niveau Ascendant"},
"SORKORL22918": {nom: "SORO", prenom: "KOROTOUM", niveau: "L2-Niveau Ascendant"},
"TRASALL24918": {nom: "TRAORE", prenom: "SALIMATA", niveau: "L2-Niveau Ascendant"},
"KOUADJL25985": {nom: "KOUAME", prenom: "ADJOUA VALERIE", niveau: "L2-Niveau Ascendant"},
"KOUAFFL20595": {nom: "KOUADIO", prenom: "AFFOUA FOFIE VANESSA", niveau: "L2-Niveau Ascendant"},
"KPAESTL20263": {nom: "KPAN", prenom: "ESTELLE", niveau: "L2-Niveau Ascendant"},
"KOMCHAL25733": {nom: "KOMAN", prenom: "CHADON VANESSA", niveau: "L2-Niveau Ascendant"},
"AGOCELL22681": {nom: "AGO", prenom: "CELINE", niveau: "L2-Niveau Ascendant"},
"OUEALIL28028": {nom: "OUEDRAOGO", prenom: "ALIZATA", niveau: "L2-Niveau Ascendant"},
"BEDPAUL27506": {nom: "BEDA", prenom: "PAULETTE", niveau: "L2-Niveau Ascendant"},
"BOUAHUL24086": {nom: "BOUAFFOU", prenom: "AHUI AHOU MARIE-VIRGINIE", niveau: "L2-Niveau Ascendant"},
"APPYAHL22285": {nom: "APPOH", prenom: "YAH PHILOMENE", niveau: "L2-Niveau Ascendant"},
"KACAPPL26620": {nom: "KACOU", prenom: "APPOH MARIE PAULE", niveau: "L2-Niveau Ascendant"},
"YAOADJL28700": {nom: "YAO", prenom: "ADJA FODJO ANNE MARIE", niveau: "L2-Niveau Ascendant"},
"YAOMARL26670": {nom: "YAO", prenom: "MARIE-DANIELLE", niveau: "L2-Niveau Ascendant"},
"TOUHOUL20313": {nom: "TOURE", prenom: "HOURIA AÏSSATA", niveau: "L2-Niveau Ascendant"},
"KOSABEL23907": {nom: "KOSSONOU", prenom: "ABENAN SUAMAN", niveau: "L2-Niveau Ascendant"},
"NIAPATL26579": {nom: "NIAYE", prenom: "PATRICIA", niveau: "L2-Niveau Ascendant"},
"OUAKATL21339": {nom: "OUATTARA", prenom: "KATI CÉLESTINE", niveau: "L2-Niveau Ascendant"},
"OUAAMIL29659": {nom: "OUATTARA", prenom: "AMINATA", niveau: "L2-Niveau Ascendant"},
"KOUKOUL23402": {nom: "KOUASSI", prenom: "KOUASSI MARIAME OUATTARA", niveau: "L2-Niveau Ascendant"},
"MONCHIL28775": {nom: "MONNET", prenom: "CHIA BLANDINE", niveau: "L2-Niveau Ascendant"},
"ATTAMAL22746": {nom: "ATTA", prenom: "AMA DJAMIA DÉBORA JESSICA", niveau: "L2-Niveau Ascendant"},
"ATSARNL27188": {nom: "ATSAIN", prenom: "ARNAULDE CECILIA", niveau: "L2-Niveau Ascendant"},
"NGUAYAL20196": {nom: "NGUESSAN", prenom: "AYA ODETTE", niveau: "L2-Niveau Ascendant"},
"SEKSOPL27909": {nom: "SEKA", prenom: "SOPIE EPIPHANIE ANGELO", niveau: "L2-Niveau Ascendant"},
  "FOFMARL33911": {nom: "FOFANA", prenom: "MARIAM", niveau: "L3-Niveau Accompli SF" },
"BASCLAL12458": {nom: "BASSOLE", prenom: "CLAUDINE", niveau: "L1-Niveau Émergent"},
"TOKPAUL16002": {nom: "TOKOU", prenom: "PAUL SAMUEL", niveau: "L1-Niveau Émergent"},



};

/**
 * Administrateurs : utilisateurs ayant accès à l'interface admin
 */
window.ADMINS = ["tirbuce", "paterne", "brice", "bbappia"]; // Liste des noms d'utilisateurs admin


